### ISSUE TITLE
Get color code output

### ISSUE THREAD

**Issue by N0edL** [NC22/HTML5-Color-Picker#11]
![image](https://user-images.githubusercontent.com/88205753/172624332-5ca01e05-1802-4cac-956e-4d8fbd58bfca.png)
how can i get that color code in code 

where can i find the fuction of that label that change  color

**Comment by NC22** [comment]
Its just build in behaviour. If you need some thing different - instead of setting input in initial config you can just use userEvent - change for example like here https://nc22.github.io/KellyC-Color-Picker/examples/test_one_colorpicer_and_multiple_inputs.html and output inforamation in way you needed.
