### ISSUE TITLE
a piece of advice

### ISSUE THREAD

**Issue by PLQin** [NC22/HTML5-Color-Picker#5]
Better have websit , the websit is project demo ;

**Comment by NC22** [comment]
Thanks for remind. Examples was hosted one year ago, but after I wasnt able to support hosting, I removed all links. Currently it's possible again to restore host

**Comment by plqin-xiaohao** [comment]
emmm ... 

Maybe you can try using your `github page`

**Comment by plqin-xiaohao** [comment]
> Thanks for remind. Examples was hosted one year ago, but after I wasnt able to support hosting, I removed all links. Currently it's possible again to restore host

`github page` : https://pages.github.com

**Comment by NC22** [comment]
Yep I think about. Currently cant find how to just link actual js files from main project without duplicate data to pages.github.com

For example If I use script from link like https://raw.githubusercontent.com/NC22/HTML5-Color-Picker/master/html5kellycolorpicker.min.js I cant load it from html page because github return wrong mime type (plain text instead of javascript)

**Comment by plqin-xiaohao** [comment]
> Yep I think about. Currently cant find how to just link actual js files from main project without duplicate data to pages.github.com
> 
> For example If I use script from link like https://raw.githubusercontent.com/NC22/HTML5-Color-Picker/master/html5kellycolorpicker.min.js I cant load it from html page because github return wrong mime type (plain text instead of javascript)

Your script, I mean :  `https://raw.githubusercontent.com/NC22/HTML5-Color-Picker/master/html5kellycolorpicker.min.js`  Is that so ? : 

```
<script src='https://raw.githubusercontent.com/NC22/HTML5-Color-Picker/master/html5kellycolorpicker.min.js'></script>
```

You can try to change it to: 

```
<script src='./html5kellycolorpicker.min.js'></script>
```

Go to try !

**Comment by NC22** [comment]
Just tested. Nope. Thats won't work

Test one with full link
https://nc22.github.io/test.html

see console log

Test two - relative link. 

https://nc22.github.io/
(source https://github.com/NC22/nc22.github.io/blob/master/index.html)
it just exclude <script> element because cant find js file in "pages" repository. May be I can specify relative from witch repositories this link, but cant find how to do that.

What I search is just use data from projects like https://github.com/NC22/HTML5-Color-Picker/ without uploading fresh javascript files to pages repository https://github.com/NC22/nc22.github.io
That would be helpfull to get always updated versions of scripts for all projects.

**Comment by plqin-xiaohao** [comment]
> I tried it :
> 
> `https://plqin.github.io/HTML5-Color-Picker/index.html` is ok ;
> 
> or
> 
> `https://plqin.github.io/HTML5-Color-Picker/demo.html` is failure ;

sound code  : 

`https://github.com/PLQin/HTML5-Color-Picker`  ;

![github com_plqin_html5-color-picker_settings](https://user-images.githubusercontent.com/41833007/50535004-a0eab800-0b7f-11e9-94f7-ed18a0125cd2.png)

**Comment by plqin-xiaohao** [comment]
> Just tested. Nope. Thats won't work
> 
> Test one with full link
> https://nc22.github.io/test.html
> 
> see console log
> 
> Test two - relative link.
> 
> https://nc22.github.io/
> (source https://github.com/NC22/nc22.github.io/blob/master/index.html)
> it just exclude <script> element because cant find js file in "pages" repository. May be I can specify relative from witch repositories this link, but cant find how to do that.
> 
> What I search is just use data from projects like https://github.com/NC22/HTML5-Color-Picker/ without uploading fresh javascript files to pages repository https://github.com/NC22/nc22.github.io
> That would be helpfull to get always updated versions of scripts for all projects.

If you have to use `https://raw.githubusercontent.com/NC22/HTML5-Color-Picker/master/html5kellycolorpicker.min.js` knife instead of a `./html5kellycolorpicker.min.js`, Then you can try a third-party hosting platform  ;

**Comment by plqin-xiaohao** [comment]
hi, NC22 ;

I am Chinese.  

Where are you from?

Look at your introduction, it seems that it is not an English speaking country

**Comment by NC22** [comment]
@PLQin Thanks, I wasn't check this method. Just tested, and now I see that this solution have more sense. Now seems every thing works fine and examples can be acessed from page, and this data is always actual and updated

http://nc22.github.io/HTML5-Color-Picker/examples/index.html

I'll recheck and add link in readme little bit later.

> Where are you from?

Yes, english is not my native language too. I'm from Russia :)
Thanks for help

**Comment by PLQin** [comment]
oh, hhh 

nice
